config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  root 'home#index'
  get '/posts', to:'posts#index'
  get 'tags/list/:tag', to: 'posts#index', as: :list_tagged_posts
  resources :topics do
    resources :posts do
      post "read_unread", on: :member
      resources :ratings
      resources :comments do
        resources :user_comment_ratings
      end
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  has_many :user_comment_ratings
  has_many :users, through: :user_comment_ratings

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_topic
  before_action :set_post
  before_action :set_comment, only: %i[ show edit update destroy ]
  # load_and_authorize_resource

  # GET /comments or /comments.json
  def index
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_post_url(@topic, @post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to topic_post_comment_url(@topic, @post, @comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to topic_post_comments_url(@topic, @post, ), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end
    def set_post
      @post = @topic.posts.find(params[:post_id])
    end
    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <%= comment.content %> |-
    <%= comment.user.email %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@topic, @post, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.text_field :post_id, type: :hidden%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", topic_post_comment_path(params[:topic_id], params[:post_id], @comment) %> |
  <%= link_to "Back to comments", topic_post_comments_path(params[:topic_id], params[:post_id]) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", topic_post_comment_path(params[:topic_id], params[:post_id], comment) %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_topic_post_comment_path(params[:topic_id], params[:post_id]) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
<%= link_to "Back to comments", topic_post_comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_topic_post_comment_path(params[:topic_id], params[:post_id], @comment) %> |
  <%= link_to "Back to comments", topic_post_comments_path(params[:topic_id], params[:post_id]) %>

  <%= button_to "Destroy this comment", topic_post_comment_path(params[:topic_id], params[:post_id], @comment),
                method: :delete, data:{turbo_confirm: 'Are you sure'} %>
</div>