config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  root 'home#index'
  get '/posts', to:'posts#index'
  get 'tags/list/:tag', to: 'posts#index', as: :list_tagged_posts
  resources :topics do
    resources :posts do
      post "read_unread", on: :member
      resources :ratings
      resources :comments do
        resources :user_comment_ratings
      end
    end
  end

end

app/models/user_comment_rating.rb
class UserCommentRating < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/controllers/user_comment_ratings_controller.rb
class UserCommentRatingsController < ApplicationController
  before_action :set_comment
  before_action :set_user_comment_rating, only: %i[ show edit update destroy ]

  # GET /user_comment_ratings or /user_comment_ratings.json
  def index
    @users = User.all.includes([:user_comment_ratings])
    # @user_comment_ratings = @comment.user_comment_ratings
  end

  # GET /user_comment_ratings/1 or /user_comment_ratings/1.json
  def show
  end

  # GET /user_comment_ratings/new
  def new
    @user_comment_rating = current_user.user_comment_ratings.new
  end

  # GET /user_comment_ratings/1/edit
  def edit
  end

  # POST /user_comment_ratings or /user_comment_ratings.json
  def create
    @user_comment_rating = current_user.user_comment_ratings.create(user_comment_rating_params)
    @user_comment_rating.comment_id = @comment.id
    @user_comment_rating.user_id = current_user.id
    respond_to do |format|
      if @user_comment_rating.save
        format.html { redirect_to topic_post_path(@topic, @post), notice: "User comment rating was successfully created." }
        format.json { render :show, status: :created, location: @user_comment_rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_comment_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_comment_ratings/1 or /user_comment_ratings/1.json
  def update
    respond_to do |format|
      if @user_comment_rating.update(user_comment_rating_params)
        format.html { redirect_to topic_post_comment_user_comment_rating_url(@topic,@post,@comment,@user_comment_rating), notice: "User comment rating was successfully updated." }
        format.json { render :show, status: :ok, location: @user_comment_rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_comment_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_comment_ratings/1 or /user_comment_ratings/1.json
  def destroy
    @user_comment_rating.destroy

    respond_to do |format|
      format.html { redirect_to topic_post_comment_user_comment_ratings_url(@topic,@post,@comment), notice: "User comment rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_comment
      if params[:comment_id]
        @comment = Comment.find(params[:comment_id])
      else
        @comment =  @comment
      end
      @post = @comment.post
      @topic = @post.topic
    end

    def set_user_comment_rating
      @user_comment_rating = UserCommentRating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_comment_rating_params
      params.require(:user_comment_rating).permit(:value, :comment_id)
    end
end

app/helpers/user_comment_ratings_helper.rb
module UserCommentRatingsHelper
end

app/views/user_comment_ratings/_form.html.erb
<%= form_with(model: [@topic, @post, comment, user_comment_rating], url: topic_post_comment_user_comment_ratings_path(@topic, @post, comment), class: "user-comment-rating-form") do |form| %>
  <% if user_comment_rating.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(user_comment_rating.errors.count, "error") %> prohibited this user_comment_rating from being saved:</h2>

      <ul>
        <% user_comment_rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="rating-options">
    <% Rating::VALUES.each do |value| %>
      <div class="rating-option">
        <%= form.radio_button(:value, value, class: "rating-input") %>
        <%= form.label(value, class: "rating-label") %>
      </div>
    <% end %>
  </div>

  <div class="submit-button">
    <%= form.submit(class: "submit-button") %>
  </div>
  </div>
<%end %>

app/views/user_comment_ratings/_ratings_by_user.html.erb
<div class="user-list">
  <% users.each do |u| %>
    <% if u.user_comment_ratings.present? %>
      <div class="user-info">
        Username: <%= u.email %>
      </div>
      <div class="user-comment-ratings">
        <% u.user_comment_ratings.each do |us| %>
          <%= render us %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user_comment_ratings/_user_comment_rating.html.erb
<div id="<%= dom_id user_comment_rating %>" class="user-comment-rating">
  <p class="rating-value">
    <strong>Value:</strong>
    <%= user_comment_rating.value %>
  </p>

  <p class="comment-id">
    <strong>Comment:</strong>
    <%= user_comment_rating.comment_id %>
  </p>

  <p class="user-id">
    <strong>User:</strong>
    <%= user_comment_rating.user_id %>
  </p>
</div>

app/views/user_comment_ratings/edit.html.erb
<h1 class="edit-user-comment-rating-title">Editing user comment rating</h1>

<%= render "form", user_comment_rating: @user_comment_rating %>

<div class="user-comment-rating-links">
  <%= link_to "Show this user comment rating", @user_comment_rating %> |
  <%= link_to "Back to user comment ratings", user_comment_ratings_path %>
</div>

app/views/user_comment_ratings/index.html.erb
<p style="color: green" class="notice"><%= notice %></p>

<h1 class="user-comment-ratings-title">User comment ratings</h1>

<div class="user-comment-ratings">
  <%# @user_comment_ratings.each do |user_comment_rating| %>
  <%#= render user_comment_rating %>
  <!--    <p>-->
  <%#= link_to "Show this user comment rating", topic_post_comment_user_comment_rating_path(@topic, @post, params[:comment_id], user_comment_rating) %>
  <!--    </p>-->
  <%# end %>
</div>

<p class="divider">-----------------------------------------------------------------------------------------------</p>
<%= render 'ratings_by_user', users: @users %>
<p class="divider">-----------------------------------------------------------------------------------------------</p>

<%= link_to "New user comment rating", new_topic_post_comment_user_comment_rating_path(params[:comment_id]), class: "new-user-comment-rating-link" %>

app/views/user_comment_ratings/new.html.erb
<h1 class="new-user-comment-rating-title">New user comment rating</h1>

<%= render "form", user_comment_rating: @user_comment_rating %>

<br>

<div class="back-link">
  <%= link_to "Back to user comment ratings", topic_post_comment_user_comment_ratings_path(@topic, @post, @comment) %>
</div>

app/views/user_comment_ratings/show.html.erb
<p class="notice" style="color: green"><%= notice %></p>

<div class="user-comment-rating">
  <%= render @user_comment_rating %>
</div>

<div class="actions">
  <%= link_to "Edit this user comment rating", edit_topic_post_comment_user_comment_rating_path(@user_comment_rating) %> |
  <%= link_to "Back to user comment ratings", topic_post_comment_user_comment_ratings_path(@user_comment_rating.comment_id) %>

  <%= button_to "Destroy this user comment rating", topic_post_comment_user_comment_ratings_path(@user_comment_rating), method: :delete, data: { turbo_confirm: 'Are you sure' } %>
</div>