config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  root 'home#index'
  get '/posts', to:'posts#index'
  get 'tags/list/:tag', to: 'posts#index', as: :list_tagged_posts
  resources :topics do
    resources :posts do
      post "read_unread", on: :member
      resources :ratings
      resources :comments do
        resources :user_comment_ratings
      end
    end
  end

end

app/models/rating.rb
class Rating < ApplicationRecord
  VALUES = (1..5)
  belongs_to :post

  validates :value, presence: true, inclusion: {in: Rating::VALUES}

  after_commit :update_post_average_rating, on: [:create, :update]
  def update_post_average_rating
    self.post.update!(rating_average: post.ratings.average(:value))
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :set_topic
  before_action :set_post
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = @post.ratings
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = @post.ratings.build
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = @post.ratings.build(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to topic_post_url(@topic, @post), notice: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to topic_post_rating_url(@topic, @post, @rating), notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to topic_post_ratings_url(@topic, @post), notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    def set_post
      @post = @topic.posts.find(params[:post_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = @post.ratings.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:value, :post_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: [@topic, @post, rating], class: 'rating-form') do |form| %>
  <% if rating.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="rating-options">
    <% Rating::VALUES.each do |value| %>
      <div class="rating-option">
        <%= form.radio_button(:value, value, class: 'rating-input') %>
        <%= form.label value, class: 'rating-label' %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.text_field :post_id, type: :hidden %>
  </div>

  <div class="submit-button">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>" class="rating-display">
  <p>
    <strong>Value:</strong>
    <%= rating.value %>
  </p>
</div>

app/views/ratings/edit.html.erb
<h1 style="color: #333;">Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div class="rating-links">
  <%= link_to "Show this rating", @rating, class: "rating-link" %> |
  <%= link_to "Back to ratings", topic_post_ratings_path(params[:topic_id], params[:post_id]), class: "rating-link" %>
</div>

app/views/ratings/index.html.erb
<p style="color: green; font-size: 18px; margin-bottom: 20px;"><%= notice %></p>

<h1 style="font-size: 24px; color: #333;">Ratings</h1>

<div id="ratings">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <p class="rating-link">
      <%= link_to "Show this rating", topic_post_rating_path(params[:topic_id], params[:post_id], rating), class: "rating-link" %>
    </p>
  <% end %>
</div>

<%= link_to "New rating", new_topic_post_rating_path(params[:topic_id], params[:post_id]), class: "new-rating-link" %>

app/views/ratings/new.html.erb
<h1 style="font-size: 24px; color: #333;">New rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back to ratings", topic_post_ratings_path(params[:topic_id], params[:post_id]), class: "back-link" %>
</div>

app/views/ratings/show.html.erb
<p style="color: green; font-size: 18px; margin-top: 10px;"> <%= notice %> </p>

<%= render @rating %>

<div class="rating-actions">
  <%= link_to "Edit this rating", edit_topic_post_rating_path(params[:topic_id], params[:post_id], @rating), class: "edit-link" %> |
  <%= link_to "Back to ratings", topic_post_ratings_path(params[:topic_id], params[:post_id]), class: "back-link" %>

  <%= button_to "Destroy this rating", topic_post_rating_path(params[:topic_id], params[:post_id], @rating),
                method: :delete, data: { turbo_confirm: 'Are you sure' }, class: "destroy-button" %>
</div>