config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  root 'home#index'
  get '/posts', to:'posts#index'
  get 'tags/list/:tag', to: 'posts#index', as: :list_tagged_posts
  resources :topics do
    resources :posts do
      post "read_unread", on: :member
      resources :ratings
      resources :comments do
        resources :user_comment_ratings
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :ratings
  has_one_attached :post_image
  has_and_belongs_to_many :users

  validates :headline, presence: true, length: {maximum: 20}
  validates :content, presence: true

  scope :having_date_between, ->(start_date, end_date) { where(created_at: start_date..end_date) }

  def self.tagged_with(name)
    Tag.find_by(name: name).posts
  end

  def self.post_topic(topic ="")
    if topic.present?
      topic.name + ' -'
    end
  end

  def self.post_read_status(post, current_user)
    post.users.include?(current_user) ? 'Read': 'Unread'
  end

  # def self.avg_rating(post="")
  #   if post.ratings.present?
  #     (post.ratings.average(:value)).round(1)
  #   else
  #     0
  #   end
  # end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_topic
  before_action :set_post, only: %i[ show edit update destroy ]
  # load_and_authorize_resource
  # skip_authorize_resource :only => :read_unread

  # GET /posts or /posts.json
  def index
    if params[:search] && params[:search][:date].present?
      start_date, end_date = params[:search][:date].split(' - ')
      @pagy, @posts = pagy(Post.having_date_between(start_date, end_date))
      puts @posts.count
    elsif params[:tag]
      @pagy, @posts = pagy(Post.tagged_with(params[:tag]))
    elsif params[:topic_id].present?
      @pagy, @posts = pagy(@topic.posts.includes(:users))
    else
      @pagy, @posts = pagy(Post.includes(:topic, :users).all)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @topic.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    sleep 0.5
    @post = @topic.posts.build(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        # CrudNotificationMailer.create_notification(@post).deliver_now
        format.html { redirect_to topic_post_url(@topic,@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js {flash.now[:error] = @post.errors.full_messages}
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        # CrudNotificationMailer.update_notification(@post).deliver_now
        format.html { redirect_to topic_post_url(@topic,@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    # CrudNotificationMailer.delete_notification(@post).deliver_now
    @post.destroy
    respond_to do |format|
      format.html { redirect_to topic_posts_url(@topic), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def read_unread
    @post.users << current_user
    head :ok
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    if params[:topic_id]
      @topic = Topic.find(params[:topic_id])
    end
  end
  def set_post
    @post = @topic.posts.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:headline, :content, :topic_id, :post_image, tag_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@topic, post], local: false) do |form| %>
  <div class="form-container">
    <% if post.errors.any? %>
      <div class="error-message">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :headline %>
      <%= form.text_field :headline, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :post_image %>
      <%= form.file_field :post_image, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :tag_ids %>
      <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name, class: "form-check-input" %>
    </div>

    <div class="form-group">
      <%= form.text_field :topic_id, type: :hidden %>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/_list_posts.html.erb
<%= render 'shared/filter_form' %>
<h1><%= Post.post_topic(@topic) %> Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <div class="post-container" id="postdiv<%= post.id %>">
      <%= render 'posts/post_container', post: post %>
    </div>
  <% end %>
</div>

<% if @topic.present? %>
  <%= link_to "New post", new_topic_post_path(@topic), remote: true, class: "new-post-link" %>
<% end %>

<p id="new-user-form"></p>

<div class="pagination">
  <%= pagy_nav(@pagy).html_safe %>
</div>

app/views/posts/_post.html.erb
<div class="post-container" id="<%= dom_id post %>">
  <p class="read-status">
    <%= Post.post_read_status(post, current_user) %>
  </p>
  <h2 class="headline"><%= post.headline %></h2>

  <p class="content">
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <div class="post-image">
    <% if post.post_image.attached? %>
      <%= image_tag post.post_image, style: "width: 300px; height: 100px" %>
    <% end %>
  </div>

  <p class="user-info">
    <strong>User :</strong>
    <%= post.user.email %>
  </p>
</div>

app/views/posts/_post_container.html.erb
<div class="post-container">
  <p class="read-status">
    <%= post.users.include?(current_user) %>
  </p>
  <h2 class="headline"><%= post.headline %></h2>

  <p class="content">
    <strong>Content:</strong>
    <%= truncate post.content, length: 50, omission: '...Read More' %>
  </p>

  <p class="rating">
    <strong>Avg Rating:</strong>
    <%= post.rating_average %>
  </p>

  <p class="comments">
    <strong>Comments:</strong>
    <%= post.comments_count %>
  </p>

  <p class="show-post-link">
    <%= link_to "Show this post", topic_post_path(post.topic, post) %>
  </p>
</div>

app/views/posts/create.js.erb
$('#loader').hide()
<% if @post.errors.any? %>
alert("ERROR(S):\n<%= escape_javascript raw @post.errors.full_messages.join("\n") %>");
<%else %>
alert("success");
$("#posts").append("<%= escape_javascript render('posts/post_container', post:@post) %>")
$("#new-user-form").hide()
<%end %>

app/views/posts/edit.html.erb
<h1 class="edit-post-heading">Editing post</h1>

<%= render "form", post: @post %>

<div class="edit-post-actions">
  <%= link_to "Show this post", topic_post_path(@post.topic_id, @post), class: "show-post-link" %> |
  <%= link_to "Back to posts", topic_posts_path(@post.topic_id), class: "back-to-posts-link" %>
</div>

app/views/posts/index.html.erb
<p class="notice"><%= notice %></p>

<div class="list-posts-container">
  <%= render 'list_posts' %>
</div>

app/views/posts/new.html.erb
<h1 class="new-post-heading">New post</h1>

<%= render "form", post: @post, class: "new-post-form" %>

<div>
  <%= link_to "Back to posts", topic_posts_path(params[:topic_id]), class: "back-to-posts-link" %>
</div>

app/views/posts/new.js.erb
let x = document.getElementById("new-user-form")
$(x).show()
$(x).html("<%= escape_javascript render('form', post:@post) %>")
$('#submit-button').on("click", function (){
    $('#loader').show()
})

app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>

<!-- Post Section -->
<div data-controller="posts" class="post-container">
  <p id="read"></p>
  <%= hidden_field_tag :topic_id, params[:topic_id] %>
  <%= hidden_field_tag :post_id, params[:id] %>
  <%= hidden_field_tag :read_status, Post.post_read_status(@post, current_user) %>
  <%= render @post %>
</div>

<!-- Actions Section -->
<div class="actions">
  <%= link_to "Edit this post", edit_topic_post_path(params[:topic_id], @post) %> |
  <%= link_to "Back to posts", topic_posts_path(params[:topic_id]) %>
  <%= button_to "Destroy this post", topic_post_path(params[:topic_id], @post),
                method: :delete, data: { turbo_confirm: 'Are you sure' } %>
</div>

<!-- Comments Section -->
<div class="comments-container">
  <div>
    <p>
      <strong>Comments:</strong>
      <%= @post.comments.size %>
    </p>
    <% @post.comments.each do |comment| %>
      <div>
        <%= link_to comment.content, topic_post_comment_path(params[:topic_id], @post, comment) %> | -
        <%= comment.user.email %> |
        <%= link_to "See Ratings", topic_post_comment_user_comment_ratings_path(@post.topic.id, @post, comment.id) %>
      </div>
      <div>
        <%= render "user_comment_ratings/form", comment: comment, user_comment_rating: current_user.user_comment_ratings.new %>
      </div>
    <% end %>
  </div>
  <div>
    <%= render 'comments/form', comment: @post.comments.new %>
  </div>
</div>

<!-- Tags Section -->
<small class="tags">
  <%=
    raw @post.tags.map(&:name).map {
      |t| link_to ('#').concat(t), list_tagged_posts_path(t)
    }.join(' ')
  %>
</small>

<!-- Ratings Section -->
<span class="ratings-container">
  <p>
    <strong>Avg Rating:</strong>
    <%= @post.rating_average %>
  </p>
  <% @post.ratings.group(:value).count.each do |key, value| %>
    <p><%= key %> star present <%= value %> times</p>
  <% end %>
</span>

<!-- Add New Rating Section -->
<div class="add-rating">
  <h2><strong>Add new rating</strong></h2>
  <%= render 'ratings/form', rating: Rating.new %>
</div>